class StationSeedService {
  static List<Map<String, dynamic>> get riyadhStations => [
        {
          'name': 'EVIQ - ROSHN Front',
          'address': 'ROSHN Front, King Salman Road, Riyadh',
          'latitude': 24.842008,
          'longitude': 46.732702,
          'connectorType': 'CCS',
          'power': 350.0,
          'fee': 'Paid',
          'rating': 4.8,
        },
        {
          'name': 'EVIQ - Hayat Mall',
          'address': 'Hayat Mall, Northern Ring Road, Riyadh',
          'latitude': 24.7682,
          'longitude': 46.7143,
          'connectorType': 'CCS',
          'power': 50.0,
          'fee': 'Paid',
          'rating': 4.5,
        },
        {
          'name': 'EVIQ - Riyadh Hub',
          'address': 'Riyadh Hub Mall, King Fahd Road, Riyadh',
          'latitude': 24.7320,
          'longitude': 46.6512,
          'connectorType': 'CCS',
          'power': 150.0,
          'fee': 'Paid',
          'rating': 4.6,
        },
        {
          'name': 'EVIQ - King Khalid International Airport',
          'address': 'King Khalid International Airport, Riyadh',
          'latitude': 24.9576,
          'longitude': 46.6988,
          'connectorType': 'CCS',
          'power': 120.0,
          'fee': 'Paid',
          'rating': 4.7,
        },
        {
          'name': 'EVIQ - Kingdom Centre',
          'address': 'Kingdom Centre Tower, Olaya Street, Riyadh',
          'latitude': 24.6911,
          'longitude': 46.6843,
          'connectorType': 'CCS',
          'power': 120.0,
          'fee': 'Paid',
          'rating': 4.7,
        },
        {
          'name': 'EVIQ - Al Nakheel Mall',
          'address': 'Al Nakheel Mall, King Fahd Road, Riyadh',
          'latitude': 24.8012,
          'longitude': 46.6589,
          'connectorType': 'CCS',
          'power': 150.0,
          'fee': 'Paid',
          'rating': 4.6,
        },
        {
          'name': 'EVIQ - Granada Mall',
          'address': 'Granada Mall, Eastern Ring Road, Riyadh',
          'latitude': 24.7521,
          'longitude': 46.7132,
          'connectorType': 'CCS',
          'power': 100.0,
          'fee': 'Paid',
          'rating': 4.5,
        },
        {
          'name': 'EVIQ - Riyadh Park Mall',
          'address': 'Riyadh Park Mall, Northern Ring Road, Riyadh',
          'latitude': 24.7744,
          'longitude': 46.6384,
          'connectorType': 'CCS',
          'power': 100.0,
          'fee': 'Paid',
          'rating': 4.4,
        },
        {
          'name': 'EVIQ - Diriyah Gate',
          'address': 'Diriyah Gate Development Authority, Riyadh',
          'latitude': 24.7342,
          'longitude': 46.5733,
          'connectorType': 'CCS',
          'power': 150.0,
          'fee': 'Paid',
          'rating': 4.8,
        },
        {
          'name': 'EVIQ - KAFD',
          'address': 'King Abdullah Financial District, Riyadh',
          'latitude': 24.7671,
          'longitude': 46.6722,
          'connectorType': 'CCS',
          'power': 150.0,
          'fee': 'Paid',
          'rating': 4.7,
        },
        {
          'name': 'EVIQ - Al Qasr Mall',
          'address': 'Al Qasr Mall, Southern Ring Road, Riyadh',
          'latitude': 24.6833,
          'longitude': 46.7167,
          'connectorType': 'CCS',
          'power': 100.0,
          'fee': 'Paid',
          'rating': 4.3,
        },
        {
          'name': 'Lucid Studio Riyadh',
          'address': 'Olaya Street, Al Olaya District, Riyadh',
          'latitude': 24.6915,
          'longitude': 46.6833,
          'connectorType': 'CCS',
          'power': 300.0,
          'fee': 'Paid',
          'rating': 4.9,
        },
        {
          'name': 'Tesla Supercharger - Kingdom Centre',
          'address': 'Kingdom Centre, Olaya Street, Riyadh',
          'latitude': 24.6877,
          'longitude': 46.6831,
          'connectorType': 'Tesla / CCS',
          'power': 250.0,
          'fee': 'Paid',
          'rating': 4.7,
        },
        {
          'name': 'Tesla Supercharger - Riyadh Front',
          'address': 'Riyadh Front Exhibition Center, Riyadh',
          'latitude': 24.8350,
          'longitude': 46.7380,
          'connectorType': 'Tesla / CCS',
          'power': 250.0,
          'fee': 'Paid',
          'rating': 4.8,
        },
        {
          'name': 'Electromin - Petromin King Fahd Road',
          'address': 'King Fahd Road, Al Olaya, Riyadh',
          'latitude': 24.7136,
          'longitude': 46.6753,
          'connectorType': 'CCS',
          'power': 50.0,
          'fee': 'Paid',
          'rating': 4.2,
        },
        {
          'name': 'Electromin - Al Yasmin',
          'address': 'Al Yasmin District, Riyadh',
          'latitude': 24.8200,
          'longitude': 46.6400,
          'connectorType': 'Type 2',
          'power': 22.0,
          'fee': 'Paid',
          'rating': 3.9,
        },
        {
          'name': 'SASCO Plus - Riyadh Qassim Highway',
          'address': 'Riyadh-Qassim Highway, Riyadh',
          'latitude': 24.9850,
          'longitude': 46.5200,
          'connectorType': 'CCS',
          'power': 150.0,
          'fee': 'Paid',
          'rating': 4.5,
        },
        {
          'name': 'Radisson Blu Hotel - EV Charging',
          'address': 'Radisson Blu Hotel, Convention Center, Riyadh',
          'latitude': 24.7600,
          'longitude': 46.6900,
          'connectorType': 'Type 2',
          'power': 22.0,
          'fee': 'Free',
          'rating': 4.3,
        },
        {
          'name': 'Four Seasons Hotel Riyadh - EV Charging',
          'address': 'Four Seasons Hotel, Kingdom Centre, Riyadh',
          'latitude': 24.6905,
          'longitude': 46.6840,
          'connectorType': 'Type 2',
          'power': 22.0,
          'fee': 'Free',
          'rating': 4.6,
        },
        {
          'name': 'EV Charging Station - Al Saadah',
          'address': 'Al Saadah District, Riyadh',
          'latitude': 24.6886,
          'longitude': 46.8309,
          'connectorType': 'CCS',
          'power': 50.0,
          'fee': 'Paid',
          'rating': 4.2,
        },
        {
          'name': 'EVIQ - North Riyadh 1',
          'address': 'North Riyadh, Riyadh',
          'latitude': 24.8456,
          'longitude': 46.7590,
          'connectorType': 'CCS',
          'power': 150.0,
          'fee': 'Paid',
          'rating': 4.5,
        },
        {
          'name': 'EVIQ - North Riyadh 2',
          'address': 'North Riyadh, Riyadh',
          'latitude': 24.8176,
          'longitude': 46.7823,
          'connectorType': 'CCS',
          'power': 150.0,
          'fee': 'Paid',
          'rating': 4.4,
        },
        {
          'name': 'Electromin - Al Rabwah 1',
          'address': 'Al Rabwah District, Riyadh',
          'latitude': 24.6982,
          'longitude': 46.7734,
          'connectorType': 'CCS',
          'power': 50.0,
          'fee': 'Paid',
          'rating': 4.1,
        },
        {
          'name': 'Electromin - Al Rabwah 2',
          'address': 'Al Rabwah District, Riyadh',
          'latitude': 24.7008,
          'longitude': 46.7699,
          'connectorType': 'CCS',
          'power': 50.0,
          'fee': 'Paid',
          'rating': 4.0,
        },
        {
          'name': 'EV Charging Station - Al Olaya',
          'address': 'Al Olaya District, Riyadh',
          'latitude': 24.7109,
          'longitude': 46.7551,
          'connectorType': 'Type 2',
          'power': 22.0,
          'fee': 'Paid',
          'rating': 3.9,
        },
        {
          'name': 'EVIQ - Al Malaz',
          'address': 'Al Malaz District, Riyadh',
          'latitude': 24.6893,
          'longitude': 46.7332,
          'connectorType': 'CCS',
          'power': 100.0,
          'fee': 'Paid',
          'rating': 4.3,
        },
        {
          'name': 'Electromin - Al Malaz',
          'address': 'Al Malaz District, Riyadh',
          'latitude': 24.6910,
          'longitude': 46.7323,
          'connectorType': 'CCS',
          'power': 50.0,
          'fee': 'Paid',
          'rating': 4.0,
        },
        {
          'name': 'E-Fill Charging Station',
          'address': 'South Riyadh',
          'latitude': 24.6619,
          'longitude': 46.7001,
          'connectorType': 'CCS',
          'power': 50.0,
          'fee': 'Paid',
          'rating': 4.1,
        },
        {
          'name': 'EVIQ - South Riyadh',
          'address': 'South Riyadh',
          'latitude': 24.5999,
          'longitude': 46.6963,
          'connectorType': 'CCS',
          'power': 100.0,
          'fee': 'Paid',
          'rating': 4.2,
        },
      ];
}
